#!/usr/bin/env python
"""Generate deterministic required reports from the v3 authoritative dataset."""
from __future__ import annotations
import datetime as dt,hashlib,json,sqlite3,subprocess
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];CAT=ROOT/'catalog';DB=CAT/'authoritative_catalogue.sqlite3';REP=CAT/'quality'/'reports';EXP=CAT/'v2'/'exports'
def now():return dt.datetime.now(dt.timezone.utc).isoformat(timespec='seconds')
def md(v):return str(v if v is not None else '').replace('|','\\|').replace('\r',' ').replace('\n',' ')
def main():
 c=sqlite3.connect(f'file:{DB.as_posix()}?mode=ro',uri=True);c.row_factory=sqlite3.Row;REP.mkdir(parents=True,exist_ok=True);EXP.mkdir(parents=True,exist_ok=True);ts=now()
 # Human-readable catalogue, ordered by source scope and row occurrence.
 lines=['# 2017 Mopar OEM Catalogue — Chrysler 300C / Dodge Challenger','',f'Generated: {ts}','','Source strings are preserved. Each table row is one exact visible source-row occurrence; repeated callouts remain separate.','']
 for v in c.execute('select * from variations order by vehicle_id,variation_id'):
  lines += [f'## {md(v["variation_source_label"])}','',f'Source route: {v["route_url"]}','']
  for leaf in c.execute("select l.*,s.source_label sublabel from catalogue_leaves l join taxonomy_nodes s on s.node_id=l.subcategory_id where l.variation_id=? and l.status!='RETIRED_SOURCE' order by s.ordinal,l.leaf_type,l.assembly_number",(v['variation_id'],)):
   rows=c.execute('select * from part_records where catalogue_leaf_id=? order by source_section,source_row_anchor,source_occurrence_ordinal',(leaf['catalogue_leaf_id'],)).fetchall()
   if not rows:continue
   lines += [f'### {md(leaf["sublabel"])}'+(f' — Diagram {leaf["assembly_number"]}: {md(leaf["diagram_title_source"])}' if leaf['leaf_type']=='DIAGRAM' else ''),'',f'Source: {leaf["source_url"]}','', '| Section | Row/callout | Occ. | Name | OEM part number | Fitment | Image state |','|---|---:|---:|---|---|---|---|']
   for r in rows:lines.append(f'| {md(r["source_section"])} | {md(r["diagram_callout_source"] or r["source_row_anchor"])} | {r["source_occurrence_ordinal"]} | {md(r["part_name_source"])} | `{md(r["oem_part_number_source"])}` | {md(r["fitment_notes_source"])} | {md(r["image_verification_status"])} |')
   lines.append('')
 (EXP/'CATALOGUE.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
 fit={r[0]:r[1] for r in c.execute('select fitment_audit_status,count(*) from part_records group by fitment_audit_status')};pn={r[0]:r[1] for r in c.execute("select case when oem_part_number_source='PART_NUMBER_NOT_DISPLAYED' then 'PART_NUMBER_NOT_DISPLAYED' else 'DISPLAYED' end,count(*) from part_records group by 1")};shared=c.execute("select count(*) from (select oem_part_number_normalized from part_records where oem_part_number_source!='PART_NUMBER_NOT_DISPLAYED' group by oem_part_number_normalized having count(distinct variation_id)>1)").fetchone()[0];pndata={'generated_at':ts,'fitment_status_counts':fit,'part_number_disposition_counts':pn,'unique_displayed_oem_part_numbers':c.execute("select count(distinct oem_part_number_normalized) from part_records where oem_part_number_source!='PART_NUMBER_NOT_DISPLAYED'").fetchone()[0],'shared_part_numbers':shared,'applicability_relationships':c.execute("select count(*) from (select distinct oem_part_number_normalized,variation_id from part_records where oem_part_number_source!='PART_NUMBER_NOT_DISPLAYED')").fetchone()[0]};(REP/'part_number_fitment_audit.json').write_text(json.dumps(pndata,indent=2)+'\n');(REP/'PART_NUMBER_FITMENT_AUDIT.md').write_text('# Part Number and Fitment Audit\n\n```json\n'+json.dumps(pndata,indent=2,ensure_ascii=False)+'\n```\n',encoding='utf-8')
 comp={'generated_at':ts,'project':{},'variations':[]};active=c.execute("select count(*) from catalogue_leaves where status!='RETIRED_SOURCE'").fetchone()[0];comp['project']={'expected_active_leaves':active,'processed':c.execute("select count(*) from catalogue_leaves where status not in ('NOT_STARTED','IN_PROGRESS','QA_FAILED') and status!='RETIRED_SOURCE'").fetchone()[0],'passed':c.execute("select count(*) from catalogue_leaves where status in ('INTEGRITY_CHECKED','QA_PASSED')").fetchone()[0],'failed':c.execute("select count(*) from catalogue_leaves where status='QA_FAILED'").fetchone()[0],'blocked':c.execute("select count(*) from catalogue_leaves where status='BLOCKED_EXTERNAL'").fetchone()[0],'unexplained':c.execute("select count(*) from catalogue_leaves where status in ('NOT_STARTED','IN_PROGRESS')").fetchone()[0],'source_rows':c.execute('select count(*) from visible_source_rows').fetchone()[0],'records':c.execute('select count(*) from part_records').fetchone()[0],'callout_rows':c.execute("select count(*) from visible_source_rows where source_section='CALLOUT_SUMMARY'").fetchone()[0],'image_observations':c.execute('select count(*) from image_observations').fetchone()[0]}
 for v in c.execute('select * from variations order by variation_id'):
  comp['variations'].append({'variation_id':v['variation_id'],'source_label':v['variation_source_label'],'expected_categories':v['expected_category_count'],'category_leaves':c.execute("select count(*) from catalogue_leaves where variation_id=? and leaf_type='CATEGORY_INDEX' and status!='RETIRED_SOURCE'",(v['variation_id'],)).fetchone()[0],'diagram_leaves':c.execute("select count(*) from catalogue_leaves where variation_id=? and leaf_type='DIAGRAM' and status!='RETIRED_SOURCE'",(v['variation_id'],)).fetchone()[0],'records':c.execute('select count(*) from part_records where variation_id=?',(v['variation_id'],)).fetchone()[0]})
 (REP/'completeness_reconciliation.json').write_text(json.dumps(comp,indent=2)+'\n');(REP/'COMPLETENESS_RECONCILIATION.md').write_text('# Completeness Reconciliation\n\n```json\n'+json.dumps(comp,indent=2,ensure_ascii=False)+'\n```\n',encoding='utf-8')
 integrity={'generated_at':ts,'sqlite_integrity':c.execute('pragma integrity_check').fetchone()[0],'foreign_key_failures':len(c.execute('pragma foreign_key_check').fetchall()),'source_snapshots':c.execute('select count(*) from source_snapshots').fetchone()[0],'image_assets':c.execute('select count(*) from image_assets').fetchone()[0],'orphan_assets':c.execute('select count(*) from image_assets a left join image_observations o on o.image_sha256=a.image_sha256 where o.image_sha256 is null').fetchone()[0],'fts_rows':c.execute('select count(*) from catalogue_fts').fetchone()[0],'part_records':c.execute('select count(*) from part_records').fetchone()[0],'git_lfs_fsck_exit':subprocess.run(['git','lfs','fsck'],cwd=ROOT,capture_output=True).returncode};(REP/'repository_integrity.json').write_text(json.dumps(integrity,indent=2)+'\n');(REP/'REPOSITORY_INTEGRITY.md').write_text('# Repository Integrity Report\n\n```json\n'+json.dumps(integrity,indent=2)+'\n```\n',encoding='utf-8');c.close();print(json.dumps({'generated_at':ts,'reports':['CATALOGUE.md','PART_NUMBER_FITMENT_AUDIT.md','COMPLETENESS_RECONCILIATION.md','REPOSITORY_INTEGRITY.md']},indent=2))
if __name__=='__main__':main()
